name: Build and test

on:
  pull_request:

jobs:
  build-test:
    name: Build and test all samples
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4

      - name: Test pekko-sample-cluster-java
        run: cd pekko-sample-cluster-java && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-scala
        run: cd pekko-sample-cluster-scala && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-client-grpc-scala
        run: cd pekko-sample-cluster-client-grpc-scala && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-client-grpc-java
        run: cd pekko-sample-cluster-client-grpc-java && mvn test

      - name: Test pekko-sample-distributed-data-java
        run: cd pekko-sample-distributed-data-java && sbt multi-jvm:test

      - name: Test pekko-sample-distributed-data-scala
        run: cd pekko-sample-distributed-data-scala && sbt multi-jvm:test

      - name: Test pekko-sample-distributed-workers-scala
        run: cd pekko-sample-distributed-workers-scala && sbt test

      - name: Test pekko-sample-fsm-java
        run: cd pekko-sample-fsm-java && mvn test

      - name: Test pekko-sample-fsm-scala
        run: cd pekko-sample-fsm-scala && sbt test

      - name: Test pekko-sample-persistence-java
        run: cd pekko-sample-persistence-java && mvn test

      - name: Test pekko-sample-persistence-scala
        run: cd pekko-sample-persistence-scala && sbt test

      - name: Test pekko-sample-persistence-dc-java
        run: cd pekko-sample-persistence-dc-java && mvn test

      - name: Test pekko-sample-persistence-dc-scala
        run: cd pekko-sample-persistence-dc-scala && sbt test

      - name: Test pekko-sample-sharding-java
        run: cd pekko-sample-sharding-java && mvn test

      - name: Test pekko-sample-sharding-scala
        run: cd pekko-sample-sharding-scala && sbt test

      - name: Test akka-sample-kafka-to-sharding-scala
        run: cd akka-sample-kafka-to-sharding-scala && sbt test

      - name: Test docs gen
        run: cd docs-gen && sbt paradox
