name: Build and test

on:
  pull_request:

jobs:
  build-test:
    name: Build and test all samples
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4

      - name: Test pekko-sample-cluster-java
        run: cd pekko-sample-cluster-java && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-scala
        run: cd pekko-sample-cluster-scala && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-client-grpc-scala
        run: cd pekko-sample-cluster-client-grpc-scala && sbt multi-jvm:test

      - name: Test pekko-sample-cluster-client-grpc-java
        run: cd pekko-sample-cluster-client-grpc-java && mvn test

      - name: Test pekko-sample-distributed-data-java
        run: cd pekko-sample-distributed-data-java && sbt multi-jvm:test

      - name: Test pekko-sample-distributed-data-scala
        run: cd pekko-sample-distributed-data-scala && sbt multi-jvm:test

      - name: Test pekko-sample-distributed-workers-scala
        run: cd pekko-sample-distributed-workers-scala && sbt test

      - name: Test pekko-sample-fsm-java
        run: cd pekko-sample-fsm-java && mvn test

      - name: Test pekko-sample-fsm-scala
        run: cd pekko-sample-fsm-scala && sbt test

      - name: Test pekko-sample-persistence-java
        run: cd pekko-sample-persistence-java && mvn test

      - name: Test pekko-sample-persistence-scala
        run: cd pekko-sample-persistence-scala && sbt test

      - name: Test pekko-sample-persistence-dc-java
        run: cd pekko-sample-persistence-dc-java && mvn test

      - name: Test pekko-sample-persistence-dc-scala
        run: cd pekko-sample-persistence-dc-scala && sbt test

      - name: Test pekko-sample-sharding-java
        run: cd pekko-sample-sharding-java && mvn test

      - name: Test pekko-sample-sharding-scala
        run: cd pekko-sample-sharding-scala && sbt test

      - name: Test pekko-sample-kafka-to-sharding-scala
        run: cd pekko-sample-kafka-to-sharding-scala && sbt test

      - name: Test pekko-sample-cluster-docker-compose-java
        run: cd pekko-sample-cluster-docker-compose-java && ./scripts/test.sh

      - name: Test pekko-sample-cluster-docker-compose-scala
        run: cd pekko-sample-cluster-docker-compose-scala && ./scripts/test.sh

      - name: Test pekko-sample-cluster-kubernetes-scala
        run: cd pekko-sample-cluster-kubernetes-scala && ./scripts/setup-minikube-for-linux.sh && ./scripts/test.sh
        
      - name: Test pekko-sample-cluster-kubernetes-java
        run: cd pekko-sample-cluster-kubernetes-java && ./scripts/setup-minikube-for-linux.sh && ./scripts/test.sh

      - name: Test docs gen
        run: cd docs-gen && sbt paradox

      # Create directory structure upfront since rsync does not create intermediate directories otherwise
      - name: Create nightly directory structure
        run: |-
          mkdir -p target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs
          mv docs-gen/pekko-sample-fsm-java/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-fsm-java/
          mv docs-gen/pekko-sample-fsm-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-fsm-scala/
          mv docs-gen/pekko-sample-sharding-java/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-sharding-java/
          mv docs-gen/pekko-sample-sharding-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-sharding-scala/
          mv docs-gen/pekko-sample-persistence-java/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-persistence-java/
          mv docs-gen/pekko-sample-persistence-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-persistence-scala/
          mv docs-gen/pekko-sample-cluster-java/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-cluster-java/
          mv docs-gen/pekko-sample-cluster-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-cluster-scala/
          mv docs-gen/pekko-sample-distributed-data-java/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-distributed-data-java/
          mv docs-gen/pekko-sample-distributed-data-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-distributed-data-scala/
          mv docs-gen/pekko-sample-distributed-workers-scala/target/paradox/site/main target/nightly-docs/docs/pekko-samples/${{ github.ref_name }}-snapshot/docs/pekko-sample-distributed-workers-scala/

      - name: Upload nightly docs
        uses: ./.github/actions/sync-nightlies
        with:
          upload: true
          switches: --archive --compress --update --delete --progress --relative
          local_path: target/nightly-docs/./docs/pekko-samples/ # The intermediate dot is to show `--relative` which paths to operate on
          remote_path: ${{ secrets.NIGHTLIES_RSYNC_PATH }}/pekko/
          remote_host: ${{ secrets.NIGHTLIES_RSYNC_HOST }}
          remote_port: ${{ secrets.NIGHTLIES_RSYNC_PORT }}
          remote_user: ${{ secrets.NIGHTLIES_RSYNC_USER }}
          remote_key: ${{ secrets.NIGHTLIES_RSYNC_KEY }}


